version: '3.8'
services:
  frontend:
    container_name: reactfront
    image: melikovimagespuller/reactfrontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8081:8081
      - 8080:8080
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s